// Archivo simplificado ya que usamos el backend externo
export const obrasPermanentes = [
  {
    id: "perm_1",
    titulo: "Laberinto de Espejos Infinitos",
    artista: "Yayoi Kusama",
    año: 2019,
    tecnica: "Instalación con espejos, LEDs y acero inoxidable",
    descripcion:
      "Una sala completamente cubierta de espejos con puntos de luz LED que crean la ilusión de un universo infinito. Cuando entras, literalmente te pierdes en el cosmos. Es como estar dentro de una galaxia de neón que nunca termina.",
    ubicacion: "Sala Permanente A - Entrada principal",
    dimensiones: "4m x 4m x 3m",
    temas: ["infinito", "cosmos", "inmersión", "puntos", "reflexión"],
    experiencia: "Solo pueden entrar 3 personas por 2 minutos - es súper exclusivo y viral",
    instagram_moment: "📸 El spot más fotografiado del museo - cada ángulo es diferente y épico",
    dato_curioso: "Los espejos crean más de 1 millón de reflejos simultáneos - literal infinito",
    vibe: "hipnótico, infinito, espacial, místico, viral",
    emoji: "✨",
  },
  {
    id: "perm_2",
    titulo: "El Grito Silencioso",
    artista: "Ai Weiwei",
    año: 2020,
    tecnica: "Instalación de porcelana y sonido",
    descripcion:
      "Miles de jarrones de porcelana tradicional china rotos y reconstruidos, cada uno con una historia de resistencia. El audio reproduce testimonios reales de jóvenes activistas. Es arte que duele pero que necesitas sentir para entender el mundo.",
    ubicacion: "Sala Permanente B - Zona central",
    dimensiones: "Instalación de 200 piezas",
    temas: ["resistencia", "tradición", "ruptura", "activismo", "memoria"],
    experiencia: "Puedes caminar entre las piezas y escuchar las historias reales",
    instagram_moment: "📱 Cada jarrón cuenta una historia - perfecto para stories con mensaje profundo",
    dato_curioso: "Cada pieza rota fue reconstruida por artesanos que perdieron sus talleres por la guerra",
    vibe: "poderoso, emotivo, político, transformador, real",
    emoji: "🏺",
  },
  {
    id: "perm_3",
    titulo: "Bosque Digital",
    artista: "Rafael Lozano-Hemmer",
    año: 2021,
    tecnica: "Instalación interactiva con sensores biométricos",
    descripcion:
      "Árboles artificiales que reaccionan a tu ritmo cardíaco y respiración. Cuando te acercas, las luces cambian según tu estado emocional. Es como si el bosque pudiera leer tu alma y responderte con colores únicos que solo tú puedes crear.",
    ubicacion: "Sala Permanente C - Zona interactiva",
    dimensiones: "12 árboles de 3m de altura",
    temas: ["biometría", "naturaleza", "tecnología", "emociones", "conexión"],
    experiencia: "Coloca tu mano en el sensor y ve cómo el bosque responde solo a ti",
    instagram_moment: "🌳 Los árboles cambian de color contigo - videos épicos garantizados para TikTok",
    dato_curioso: "El sistema puede detectar hasta 15 emociones diferentes y crear patrones únicos",
    vibe: "mágico, conectivo, natural-tech, personal, interactivo",
    emoji: "🌲",
  },
  {
    id: "perm_4",
    titulo: "Memorias Fragmentadas",
    artista: "Doris Salcedo",
    año: 2018,
    tecnica: "Escultura en concreto, metal y objetos personales",
    descripcion:
      "Una grieta gigante en el suelo del museo llena de objetos personales de víctimas de violencia. Caminas sobre ella y sientes el peso de las historias no contadas. Es arte que te confronta con la realidad y te hace reflexionar sobre la vida.",
    ubicacion: "Sala Permanente D - Pasillo principal",
    dimensiones: "15m de longitud x 1m de ancho",
    temas: ["memoria", "violencia", "duelo", "objetos", "ausencia"],
    experiencia: "Caminas literalmente sobre la historia - es intenso pero necesario",
    instagram_moment: "📷 Fotos que hacen reflexionar - contenido con propósito y significado real",
    dato_curioso: "Cada objeto fue donado por familias reales afectadas por la violencia en Colombia",
    vibe: "profundo, conmovedor, histórico, sanador, reflexivo",
    emoji: "🕊️",
  },
]
